#if !NETFRAMEWORK
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using LibCpp2IL;
using LibCpp2IL.BinaryStructures;
using LibCpp2IL.Metadata;
using LibCpp2IL.Reflection;
using Newtonsoft.Json;

namespace UnityRift
{
    /// <summary>
    /// Writes Il2CppDumper-compatible reverse-engineering helpers from the LibCpp2IL state that
    /// Cpp2IL leaves loaded: <c>script.json</c> (method/metadata/string symbols + function starts,
    /// consumed by the bundled <c>ghidra.py</c> / <c>ghidra_with_struct.py</c>), <c>stringliteral.json</c>,
    /// <c>il2cpp.h</c> (C struct layouts: <c>_o</c>/<c>_Fields</c>/<c>_c</c>/<c>_VTable</c>/<c>_StaticFields</c>/<c>_array</c>)
    /// and <c>il2cpp_ghidra.h</c> (same header pre-processed for Ghidra's C parser), plus
    /// <c>il2cpp_info.json</c> (image base, versions, counts). Output formats follow Il2CppDumper
    /// (MIT, Perfare) so its Ghidra/IDA scripts work unchanged.
    /// </summary>
    public static class Il2CppGhidraExporter
    {
        #region JSON model (Il2CppDumper's ScriptJson)

        public class ScriptJson
        {
            public List<ScriptMethod> ScriptMethod = new List<ScriptMethod>();
            public List<ScriptString> ScriptString = new List<ScriptString>();
            public List<ScriptMetadata> ScriptMetadata = new List<ScriptMetadata>();
            public List<ScriptMetadataMethod> ScriptMetadataMethod = new List<ScriptMetadataMethod>();
            public ulong[] Addresses;
        }

        public class ScriptMethod
        {
            public ulong Address;
            public string Name;
            public string Signature;
            public string TypeSignature;
        }

        public class ScriptString
        {
            public ulong Address;
            public string Value;
        }

        public class ScriptMetadata
        {
            public ulong Address;
            public string Name;
            public string Signature;
        }

        public class ScriptMetadataMethod
        {
            public ulong Address;
            public string Name;
            public ulong MethodAddress;
        }

        public class Il2CppInfo
        {
            public string Binary;
            public string Metadata;
            public string UnityVersion;
            public float MetadataVersion;
            public string ImageBase;      // hex; VA = ImageBase + RVA (Ghidra: currentProgram.getImageBase())
            public int PointerSize;
            public int Methods, GenericMethods, Strings, MetadataSymbols, MetadataMethods, FunctionStarts, Structs;
            public string HeaderVersionNote;
        }

        #endregion

        public static readonly string[] OutputFiles =
        {
            "script.json", "stringliteral.json", "il2cpp.h", "il2cpp_ghidra.h", "il2cpp_info.json",
        };
        public static readonly string[] ScriptFiles =
        {
            "ghidra.py", "ghidra_with_struct.py", "il2cpp_header_to_ghidra.py", "LICENSE-Il2CppDumper.txt",
        };

        /// <summary>Writes all outputs into <paramref name="folder"/>. Requires LibCpp2IL to be initialised (call inside Cpp2IL processing).</summary>
        public static Il2CppInfo Write(string folder, string binaryPath, string metadataPath, string unityVersion, Action<string> log = null)
        {
            var gen = new Generator(log, binaryPath);
            var info = gen.Run(folder);
            info.Binary = binaryPath;
            info.Metadata = metadataPath;
            info.UnityVersion = unityVersion;
            File.WriteAllText(Path.Combine(folder, "il2cpp_info.json"), JsonConvert.SerializeObject(info, Formatting.Indented));
            WriteScripts(folder);
            return info;
        }

        /// <summary>Writes the bundled Ghidra scripts (Il2CppDumper, MIT) into <paramref name="folder"/>/ghidra.</summary>
        public static void WriteScripts(string folder)
        {
            var dir = Path.Combine(folder, "ghidra");
            Directory.CreateDirectory(dir);
            var asm = typeof(Il2CppGhidraExporter).Assembly;
            foreach (var name in ScriptFiles)
            {
                using (var s = asm.GetManifestResourceStream("ghidra." + name))
                {
                    if (s == null) continue;
                    using (var f = File.Create(Path.Combine(dir, name)))
                        s.CopyTo(f);
                }
            }
            File.WriteAllText(Path.Combine(dir, "README.txt"), GhidraReadme);
        }

        public const string GhidraReadme =
@"IL2CPP reverse-engineering package (generated by AssetStudioMod, formats compatible with Il2CppDumper)

Files (one folder up):
  script.json        method names/signatures (RVA), string literals, metadata symbols, function starts
  stringliteral.json string literals with RVAs
  il2cpp.h           C struct layouts of every managed type (Foo_o object, Foo_Fields, Foo_c class, Foo_VTable, Foo_array)
  il2cpp_ghidra.h    il2cpp.h pre-processed for Ghidra (typedefs added, ': Parent_Fields' inheritance flattened)
  il2cpp_info.json   image base, pointer size, Unity/metadata versions, counts

Ghidra workflow:
  1. Import GameAssembly.dll / libil2cpp.so into Ghidra and let auto-analysis finish.
  2. (Optional, for typed signatures) File > Parse C Source... : add il2cpp_ghidra.h, Parse to Program.
  3. Window > Script Manager > add this 'ghidra' folder as a script directory, run
       ghidra.py              names functions/strings/metadata (no header needed)
       ghidra_with_struct.py  same + applies C signatures/types (needs step 2)
     and pick script.json when asked.
  All addresses in script.json are RVAs; the scripts add currentProgram.getImageBase().

With an agent + Ghidra MCP: use AssetStudioModCLI '-m il2cpp --il2cpp-lookup <name|0xRVA|0xVA>' (or the
MCP tools il2cpp_lookup / il2cpp_strings) to translate between managed names and addresses while decompiling.
";

        #region Generator

        private sealed class StructInfo
        {
            public string TypeName;
            public bool IsValueType;
            public string Parent;
            public readonly List<(string type, string name, bool isValueType, bool isCustom)> Fields = new List<(string, string, bool, bool)>();
            public readonly List<(string type, string name, bool isValueType, bool isCustom)> StaticFields = new List<(string, string, bool, bool)>();
            public string[] VTable = Array.Empty<string>();
        }

        private sealed class Generator
        {
            private readonly Action<string> log;
            private readonly string binaryPath;
            private readonly Il2CppBinary bin = LibCpp2IlMain.Binary;
            private readonly Il2CppMetadata md = LibCpp2IlMain.TheMetadata;
            private readonly float mv = LibCpp2IlMain.MetadataVersion;

            private readonly Dictionary<Il2CppTypeDefinition, string> structNameDic = new Dictionary<Il2CppTypeDefinition, string>();
            private readonly HashSet<string> structNameSet = new HashSet<string>(StringComparer.Ordinal);
            private readonly Dictionary<string, StructInfo> structByName = new Dictionary<string, StructInfo>(StringComparer.Ordinal);
            private readonly List<StructInfo> structList = new List<StructInfo>();
            private readonly HashSet<StructInfo> emitted = new HashSet<StructInfo>();
            private readonly Dictionary<string, (Il2CppTypeDefinition def, Il2CppGenericInst inst)> pendingGenerics = new Dictionary<string, (Il2CppTypeDefinition, Il2CppGenericInst)>(StringComparer.Ordinal);
            private readonly Dictionary<string, string> genericStructNames = new Dictionary<string, string>(StringComparer.Ordinal); // key -> struct name
            private readonly StringBuilder arrayHeader = new StringBuilder();
            private readonly HashSet<string> arrayNames = new HashSet<string>(StringComparer.Ordinal);

            public Generator(Action<string> log, string binaryPath) { this.log = log; this.binaryPath = binaryPath; }

            public Il2CppInfo Run(string folder)
            {
                var info = new Il2CppInfo { MetadataVersion = mv, PointerSize = PointerSize() };
                var json = new ScriptJson();

                // 1) unique struct names for every type definition
                foreach (var td in md.typeDefs)
                    structNameDic[td] = Unique(FixName(TypeDefDisplayName(td)));

                // 2) methods
                ulong imageBase = 0;
                foreach (var td in md.typeDefs)
                {
                    AddStruct(td);
                    var typeName = TypeDefDisplayName(td);
                    foreach (var m in td.Methods ?? Array.Empty<Il2CppMethodDefinition>())
                    {
                        if (m.MethodPointer == 0) continue;
                        if (imageBase == 0 && m.Rva != 0 && m.MethodPointer > m.Rva) imageBase = m.MethodPointer - m.Rva;
                        var sm = new ScriptMethod { Address = bin.GetRva(m.MethodPointer), Name = typeName + "$$" + m.Name };
                        BuildSignature(sm, m, td, null, null);
                        json.ScriptMethod.Add(sm);
                    }
                }
                info.Methods = json.ScriptMethod.Count;

                // generic method instantiations
                foreach (var pair in bin.ConcreteGenericImplementationsByAddress)
                {
                    if (pair.Key == 0 || pair.Value == null || pair.Value.Count == 0) continue;
                    var r = pair.Value[0];
                    try
                    {
                        var typeName = TypeDefDisplayName(r.DeclaringType) + GenericArgs(r.TypeGenericParams);
                        var methodName = r.BaseMethod.Name + GenericArgs(r.MethodGenericParams);
                        var sm = new ScriptMethod { Address = bin.GetRva(pair.Key), Name = typeName + "$$" + methodName };
                        BuildSignature(sm, r.BaseMethod, r.DeclaringType, null, null);
                        json.ScriptMethod.Add(sm);
                        info.GenericMethods++;
                    }
                    catch (Exception ex)
                    {
                        log?.Invoke($"[il2cpp] generic method at 0x{pair.Key:X}: {ex.Message}");
                    }
                }
                info.ImageBase = "0x" + imageBase.ToString("X");

                // 3) function starts
                var pointers = new HashSet<ulong>();
                foreach (var td in md.typeDefs)
                    foreach (var m in td.Methods ?? Array.Empty<Il2CppMethodDefinition>())
                        if (m.MethodPointer != 0) pointers.Add(m.MethodPointer);
                foreach (var k in bin.ConcreteGenericImplementationsByAddress.Keys) pointers.Add(k);
                if (mv < 29 && bin.AllCustomAttributeGenerators != null)
                    foreach (var p in bin.AllCustomAttributeGenerators) pointers.Add(p);
                for (var i = 0; i < md.imageDefinitions.Length; i++)
                {
                    try
                    {
                        var ptrs = bin.GetCodegenModuleMethodPointers(i);
                        if (ptrs != null) foreach (var p in ptrs) pointers.Add(p);
                    }
                    catch { /* pre-24.2 has no codegen modules */ }
                }
                pointers.Remove(0);
                json.Addresses = pointers.Select(p => bin.GetRva(p)).OrderBy(x => x).ToArray();
                info.FunctionStarts = json.Addresses.Length;

                // 4) metadata usages (type infos, method infos, field infos, string literals)
                foreach (var u in EnumerateMetadataUsages())
                    AddUsage(json, u);
                info.Strings = json.ScriptString.Count;
                info.MetadataSymbols = json.ScriptMetadata.Count;
                info.MetadataMethods = json.ScriptMetadataMethod.Count;

                // 5) write json
                var settings = new JsonSerializerSettings { Formatting = Formatting.Indented };
                File.WriteAllText(Path.Combine(folder, "script.json"), JsonConvert.SerializeObject(json, settings));
                var literals = json.ScriptString.Select(s => new { value = s.Value, address = "0x" + s.Address.ToString("X") }).ToArray();
                File.WriteAllText(Path.Combine(folder, "stringliteral.json"), JsonConvert.SerializeObject(literals, settings), new UTF8Encoding(false));

                // 6) header
                // generic instances discovered while parsing signatures/fields (may discover more while emitting)
                var header = new StringBuilder();
                var progress = true;
                while (progress)
                {
                    progress = false;
                    foreach (var kv in pendingGenerics.ToList())
                    {
                        if (structByName.ContainsKey(kv.Key + "_o")) continue;
                        AddGenericStruct(kv.Key, kv.Value.def, kv.Value.inst);
                        progress = true;
                    }
                }
                foreach (var si in structList)
                    header.Append(Emit(si));
                info.Structs = structList.Count;

                var sb = new StringBuilder();
                sb.Append("// Generated by UnityRift (formats after Il2CppDumper). Metadata version ").Append(mv).Append("\r\n");
                sb.Append(Il2CppHeaderConstants.GenericHeader);
                string note = null;
                if (mv == 22) sb.Append(Il2CppHeaderConstants.HeaderV22);
                else if (mv < 24.1f) sb.Append(Il2CppHeaderConstants.HeaderV240);
                else if (mv < 24.2f) sb.Append(Il2CppHeaderConstants.HeaderV241);
                else if (mv < 27) sb.Append(Il2CppHeaderConstants.HeaderV242);
                else if (mv < 29) sb.Append(Il2CppHeaderConstants.HeaderV27);
                else
                {
                    sb.Append(Il2CppHeaderConstants.HeaderV29);
                    if (mv > 31)
                    {
                        note = $"metadata v{mv} is newer than the known Il2CppClass layouts; the v29 layout (Il2CppClass_1/_2) is used and may be slightly off for Il2CppClass internals. Object/field layouts (_o/_Fields) come from real field offsets and are unaffected.";
                        sb.Append("// NOTE: ").Append(note).Append("\r\n");
                    }
                }
                info.HeaderVersionNote = note;
                sb.Append(header);
                sb.Append(arrayHeader);
                var h = sb.ToString();
                File.WriteAllText(Path.Combine(folder, "il2cpp.h"), h);
                File.WriteAllText(Path.Combine(folder, "il2cpp_ghidra.h"), GhidraHeaderPrefix + Regex.Replace(h, @": (\w+) \{", "{\n\t$1 super;"));
                return info;
            }

            private const string GhidraHeaderPrefix =
                "typedef unsigned __int8 uint8_t;\ntypedef unsigned __int16 uint16_t;\ntypedef unsigned __int32 uint32_t;\ntypedef unsigned __int64 uint64_t;\n" +
                "typedef __int8 int8_t;\ntypedef __int16 int16_t;\ntypedef __int32 int32_t;\ntypedef __int64 int64_t;\n" +
                "typedef __int64 intptr_t;\ntypedef __int64 uintptr_t;\ntypedef unsigned __int64 size_t;\ntypedef _Bool bool;\n";

            #region names

            private int PointerSize()
            {
                try
                {
                    var p = bin.GetType().GetProperty("is32Bit", BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance)
                            ?? typeof(Il2CppBinary).GetProperty("is32Bit", BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
                    if (p != null && p.GetValue(bin) is bool b) return b ? 4 : 8;
                    var f = bin.GetType().GetField("is32Bit", BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.FlattenHierarchy);
                    if (f != null && f.GetValue(bin) is bool b2) return b2 ? 4 : 8;
                }
                catch { /* ignore */ }
                return 8;
            }

            private static readonly HashSet<string> CKeywords = new HashSet<string>
            {
                "auto","break","case","char","const","continue","default","do","double","else","enum","extern","float","for","goto","if",
                "int","long","register","return","short","signed","sizeof","static","struct","switch","typedef","union","unsigned","void",
                "volatile","while","bool","class","new","delete","this","template","typename","namespace","using","try","catch","throw",
                "inline","virtual","public","private","protected","friend","operator","true","false","near","far","huge","interrupt",
                "cdecl","stdcall","fastcall","thiscall","pascal","asm","export","import","module","in","out","ref",
            };

            private static string FixName(string s)
            {
                if (string.IsNullOrEmpty(s)) return "_";
                if (CKeywords.Contains(s)) return "_" + s;
                var r = Regex.Replace(s, "[^a-zA-Z0-9_]", "_");
                return char.IsDigit(r[0]) ? "_" + r : r;
            }

            private string Unique(string name)
            {
                var n = name;
                var i = 1;
                while (!structNameSet.Add(n)) n = $"{name}_{i++}";
                return n;
            }

            /// <summary>Namespace.Outer.Inner (arity kept, e.g. List`1) — used for symbol names.</summary>
            private static string TypeDefDisplayName(Il2CppTypeDefinition td)
            {
                var chain = new List<string>();
                var t = td;
                var guard = 0;
                while (t != null && guard++ < 32)
                {
                    chain.Add(t.Name);
                    t = t.DeclaringType;
                }
                chain.Reverse();
                var ns = td.Namespace;
                var root = td;
                guard = 0;
                while (root.DeclaringType != null && guard++ < 32) root = root.DeclaringType;
                ns = root.Namespace;
                return (string.IsNullOrEmpty(ns) ? "" : ns + ".") + string.Join(".", chain);
            }

            private string DisplayName(Il2CppTypeReflectionData r)
            {
                if (r == null) return "?";
                if (r.isArray) return DisplayName(r.arrayType) + "[" + new string(',', Math.Max(0, r.arrayRank - 1)) + "]";
                if (r.isPointer && r.arrayType != null) return DisplayName(r.arrayType) + "*";
                if (!r.isType) return r.variableGenericParamName ?? "T";
                var name = r.baseType != null ? TypeDefDisplayName(r.baseType) : "?";
                if (r.isGenericType && r.genericParams != null && r.genericParams.Length > 0)
                    name = StripArity(name) + "<" + string.Join(", ", r.genericParams.Select(DisplayName)) + ">";
                return name;
            }

            private string GenericArgs(Il2CppTypeReflectionData[] args)
            {
                if (args == null || args.Length == 0) return "";
                return "<" + string.Join(", ", args.Select(DisplayName)) + ">";
            }

            private static string StripArity(string name)
            {
                var i = name.IndexOf('`');
                return i < 0 ? name : Regex.Replace(name, "`[0-9]+", "");
            }

            /// <summary>C# style display name of an Il2CppType (used for metadata symbol names).</summary>
            private string DisplayName(Il2CppType t, Il2CppGenericInst classInst, Il2CppGenericInst methodInst)
            {
                switch (t.Type)
                {
                    case Il2CppTypeEnum.IL2CPP_TYPE_VOID: return "System.Void";
                    case Il2CppTypeEnum.IL2CPP_TYPE_BOOLEAN: return "System.Boolean";
                    case Il2CppTypeEnum.IL2CPP_TYPE_CHAR: return "System.Char";
                    case Il2CppTypeEnum.IL2CPP_TYPE_I1: return "System.SByte";
                    case Il2CppTypeEnum.IL2CPP_TYPE_U1: return "System.Byte";
                    case Il2CppTypeEnum.IL2CPP_TYPE_I2: return "System.Int16";
                    case Il2CppTypeEnum.IL2CPP_TYPE_U2: return "System.UInt16";
                    case Il2CppTypeEnum.IL2CPP_TYPE_I4: return "System.Int32";
                    case Il2CppTypeEnum.IL2CPP_TYPE_U4: return "System.UInt32";
                    case Il2CppTypeEnum.IL2CPP_TYPE_I8: return "System.Int64";
                    case Il2CppTypeEnum.IL2CPP_TYPE_U8: return "System.UInt64";
                    case Il2CppTypeEnum.IL2CPP_TYPE_R4: return "System.Single";
                    case Il2CppTypeEnum.IL2CPP_TYPE_R8: return "System.Double";
                    case Il2CppTypeEnum.IL2CPP_TYPE_STRING: return "System.String";
                    case Il2CppTypeEnum.IL2CPP_TYPE_OBJECT: return "System.Object";
                    case Il2CppTypeEnum.IL2CPP_TYPE_I: return "System.IntPtr";
                    case Il2CppTypeEnum.IL2CPP_TYPE_U: return "System.UIntPtr";
                    case Il2CppTypeEnum.IL2CPP_TYPE_TYPEDBYREF: return "System.TypedReference";
                    case Il2CppTypeEnum.IL2CPP_TYPE_PTR: return DisplayName(t.GetEncapsulatedType(), classInst, methodInst) + "*";
                    case Il2CppTypeEnum.IL2CPP_TYPE_BYREF: return DisplayName(t.GetEncapsulatedType(), classInst, methodInst) + "&";
                    case Il2CppTypeEnum.IL2CPP_TYPE_SZARRAY: return DisplayName(t.GetEncapsulatedType(), classInst, methodInst) + "[]";
                    case Il2CppTypeEnum.IL2CPP_TYPE_ARRAY: return DisplayName(t.GetArrayElementType(), classInst, methodInst) + "[" + new string(',', Math.Max(0, t.GetArrayRank() - 1)) + "]";
                    case Il2CppTypeEnum.IL2CPP_TYPE_VALUETYPE:
                    case Il2CppTypeEnum.IL2CPP_TYPE_CLASS:
                        return TypeDefDisplayName(t.AsClass());
                    case Il2CppTypeEnum.IL2CPP_TYPE_GENERICINST:
                        {
                            var gc = t.GetGenericClass();
                            var args = gc.Context?.ClassInst?.Types ?? Array.Empty<Il2CppType>();
                            return StripArity(TypeDefDisplayName(gc.TypeDefinition)) + "<" + string.Join(", ", args.Select(a => DisplayName(a, classInst, methodInst))) + ">";
                        }
                    case Il2CppTypeEnum.IL2CPP_TYPE_VAR:
                    case Il2CppTypeEnum.IL2CPP_TYPE_MVAR:
                        {
                            var resolved = ResolveGenericParam(t, classInst, methodInst);
                            if (resolved != null) return DisplayName(resolved, null, null);
                            try { return t.GetGenericParameterDef()?.Name ?? "T"; } catch { return "T"; }
                        }
                    default:
                        return t.Type.ToString();
                }
            }

            private static Il2CppType ResolveGenericParam(Il2CppType t, Il2CppGenericInst classInst, Il2CppGenericInst methodInst)
            {
                var inst = t.Type == Il2CppTypeEnum.IL2CPP_TYPE_VAR ? classInst : (methodInst ?? classInst);
                if (inst == null) return null;
                try
                {
                    var gp = t.GetGenericParameterDef();
                    var idx = gp.genericParameterIndexInOwner;
                    var types = inst.Types;
                    if (types != null && idx < types.Length) return types[idx];
                }
                catch { /* ignore */ }
                return null;
            }

            #endregion

            #region C types

            /// <summary>Base struct name (without _o/_c suffix) for a type; registers arrays/generic instances on the way.</summary>
            private string StructName(Il2CppType t, Il2CppGenericInst classInst, Il2CppGenericInst methodInst)
            {
                switch (t.Type)
                {
                    case Il2CppTypeEnum.IL2CPP_TYPE_PTR:
                    case Il2CppTypeEnum.IL2CPP_TYPE_BYREF:
                        return StructName(t.GetEncapsulatedType(), classInst, methodInst);
                    case Il2CppTypeEnum.IL2CPP_TYPE_SZARRAY:
                        return ArrayStruct(t.GetEncapsulatedType(), classInst, methodInst);
                    case Il2CppTypeEnum.IL2CPP_TYPE_ARRAY:
                        return ArrayStruct(t.GetArrayElementType(), classInst, methodInst);
                    case Il2CppTypeEnum.IL2CPP_TYPE_GENERICINST:
                        return GenericStructName(t, classInst, methodInst);
                    case Il2CppTypeEnum.IL2CPP_TYPE_VAR:
                    case Il2CppTypeEnum.IL2CPP_TYPE_MVAR:
                        {
                            var r = ResolveGenericParam(t, classInst, methodInst);
                            return r != null ? StructName(r, null, null) : "System_Object";
                        }
                    default:
                        {
                            var td = TypeDefOf(t);
                            return td != null && structNameDic.TryGetValue(td, out var n) ? n : "System_Object";
                        }
                }
            }

            private Il2CppTypeDefinition TypeDefOf(Il2CppType t)
            {
                try
                {
                    switch (t.Type)
                    {
                        case Il2CppTypeEnum.IL2CPP_TYPE_VALUETYPE:
                        case Il2CppTypeEnum.IL2CPP_TYPE_CLASS:
                            return t.AsClass();
                        case Il2CppTypeEnum.IL2CPP_TYPE_GENERICINST:
                            return t.GetGenericClass().TypeDefinition;
                        default:
                            return t.CoerceToUnderlyingTypeDefinition();
                    }
                }
                catch
                {
                    return null;
                }
            }

            private string ArrayStruct(Il2CppType elem, Il2CppGenericInst classInst, Il2CppGenericInst methodInst)
            {
                var elemStruct = StructName(elem, classInst, methodInst);
                var name = elemStruct + "_array";
                if (arrayNames.Add(name))
                {
                    arrayHeader.Append("struct ").Append(name).Append(" {\n\tIl2CppObject obj;\n\tIl2CppArrayBounds *bounds;\n\til2cpp_array_size_t max_length;\n\t")
                        .Append(ParseType(elem, classInst, methodInst)).Append(" m_Items[65535];\n};\n");
                }
                return name;
            }

            private string GenericStructName(Il2CppType t, Il2CppGenericInst classInst, Il2CppGenericInst methodInst)
            {
                var gc = t.GetGenericClass();
                var td = gc.TypeDefinition;
                var inst = gc.Context?.ClassInst;
                var args = inst?.Types ?? Array.Empty<Il2CppType>();
                var key = FixName(StripArity(structNameDic.TryGetValue(td, out var baseName) ? baseName : TypeDefDisplayName(td)))
                          + "_" + string.Join("_", args.Select(a => FixName(DisplayName(a, classInst, methodInst)))) + "_";
                if (!genericStructNames.TryGetValue(key, out var name))
                {
                    name = Unique(key);
                    genericStructNames[key] = name;
                    // Resolve VAR/MVAR args against the current context so the struct has concrete field types.
                    if (inst != null && args.Any(a => a.Type == Il2CppTypeEnum.IL2CPP_TYPE_VAR || a.Type == Il2CppTypeEnum.IL2CPP_TYPE_MVAR))
                        pendingGenerics[name] = (td, null);
                    else
                        pendingGenerics[name] = (td, inst);
                }
                return name;
            }

            /// <summary>C type used for fields/parameters (Il2CppDumper's ParseType).</summary>
            private string ParseType(Il2CppType t, Il2CppGenericInst classInst, Il2CppGenericInst methodInst)
            {
                switch (t.Type)
                {
                    case Il2CppTypeEnum.IL2CPP_TYPE_VOID: return "void";
                    case Il2CppTypeEnum.IL2CPP_TYPE_BOOLEAN: return "bool";
                    case Il2CppTypeEnum.IL2CPP_TYPE_CHAR: return "uint16_t";
                    case Il2CppTypeEnum.IL2CPP_TYPE_I1: return "int8_t";
                    case Il2CppTypeEnum.IL2CPP_TYPE_U1: return "uint8_t";
                    case Il2CppTypeEnum.IL2CPP_TYPE_I2: return "int16_t";
                    case Il2CppTypeEnum.IL2CPP_TYPE_U2: return "uint16_t";
                    case Il2CppTypeEnum.IL2CPP_TYPE_I4: return "int32_t";
                    case Il2CppTypeEnum.IL2CPP_TYPE_U4: return "uint32_t";
                    case Il2CppTypeEnum.IL2CPP_TYPE_I8: return "int64_t";
                    case Il2CppTypeEnum.IL2CPP_TYPE_U8: return "uint64_t";
                    case Il2CppTypeEnum.IL2CPP_TYPE_R4: return "float";
                    case Il2CppTypeEnum.IL2CPP_TYPE_R8: return "double";
                    case Il2CppTypeEnum.IL2CPP_TYPE_STRING: return "System_String_o*";
                    case Il2CppTypeEnum.IL2CPP_TYPE_I: return "intptr_t";
                    case Il2CppTypeEnum.IL2CPP_TYPE_U: return "uintptr_t";
                    case Il2CppTypeEnum.IL2CPP_TYPE_OBJECT:
                    case Il2CppTypeEnum.IL2CPP_TYPE_TYPEDBYREF:
                        return "Il2CppObject*";
                    case Il2CppTypeEnum.IL2CPP_TYPE_PTR:
                    case Il2CppTypeEnum.IL2CPP_TYPE_BYREF:
                        return ParseType(t.GetEncapsulatedType(), classInst, methodInst) + "*";
                    case Il2CppTypeEnum.IL2CPP_TYPE_SZARRAY:
                        return ArrayStruct(t.GetEncapsulatedType(), classInst, methodInst) + "*";
                    case Il2CppTypeEnum.IL2CPP_TYPE_ARRAY:
                        return ArrayStruct(t.GetArrayElementType(), classInst, methodInst) + "*";
                    case Il2CppTypeEnum.IL2CPP_TYPE_VALUETYPE:
                        {
                            var td = t.AsClass();
                            if (td.IsEnumType && td.EnumUnderlyingType != null) return ParseType(td.EnumUnderlyingType, classInst, methodInst);
                            return structNameDic[td] + "_o";
                        }
                    case Il2CppTypeEnum.IL2CPP_TYPE_CLASS:
                        return structNameDic[t.AsClass()] + "_o*";
                    case Il2CppTypeEnum.IL2CPP_TYPE_GENERICINST:
                        {
                            var td = t.GetGenericClass().TypeDefinition;
                            var name = GenericStructName(t, classInst, methodInst);
                            if (td.IsValueType)
                            {
                                if (td.IsEnumType && td.EnumUnderlyingType != null) return ParseType(td.EnumUnderlyingType, classInst, methodInst);
                                return name + "_o";
                            }
                            return name + "_o*";
                        }
                    case Il2CppTypeEnum.IL2CPP_TYPE_VAR:
                    case Il2CppTypeEnum.IL2CPP_TYPE_MVAR:
                        {
                            var r = ResolveGenericParam(t, classInst, methodInst);
                            return r != null ? ParseType(r, null, null) : "Il2CppObject*";
                        }
                    default:
                        return "void*";
                }
            }

            private bool IsValueTypeStruct(Il2CppType t, Il2CppGenericInst classInst, Il2CppGenericInst methodInst)
            {
                switch (t.Type)
                {
                    case Il2CppTypeEnum.IL2CPP_TYPE_VALUETYPE: return !t.AsClass().IsEnumType;
                    case Il2CppTypeEnum.IL2CPP_TYPE_GENERICINST: { var td = t.GetGenericClass().TypeDefinition; return td.IsValueType && !td.IsEnumType; }
                    case Il2CppTypeEnum.IL2CPP_TYPE_VAR:
                    case Il2CppTypeEnum.IL2CPP_TYPE_MVAR: { var r = ResolveGenericParam(t, classInst, methodInst); return r != null && IsValueTypeStruct(r, null, null); }
                    default: return false;
                }
            }

            private bool IsCustomType(Il2CppType t, Il2CppGenericInst classInst, Il2CppGenericInst methodInst)
            {
                switch (t.Type)
                {
                    case Il2CppTypeEnum.IL2CPP_TYPE_PTR:
                    case Il2CppTypeEnum.IL2CPP_TYPE_BYREF: return IsCustomType(t.GetEncapsulatedType(), classInst, methodInst);
                    case Il2CppTypeEnum.IL2CPP_TYPE_STRING:
                    case Il2CppTypeEnum.IL2CPP_TYPE_CLASS:
                    case Il2CppTypeEnum.IL2CPP_TYPE_ARRAY:
                    case Il2CppTypeEnum.IL2CPP_TYPE_SZARRAY: return true;
                    case Il2CppTypeEnum.IL2CPP_TYPE_VALUETYPE: return !t.AsClass().IsEnumType;
                    case Il2CppTypeEnum.IL2CPP_TYPE_GENERICINST: return !t.GetGenericClass().TypeDefinition.IsEnumType;
                    case Il2CppTypeEnum.IL2CPP_TYPE_VAR:
                    case Il2CppTypeEnum.IL2CPP_TYPE_MVAR: { var r = ResolveGenericParam(t, classInst, methodInst); return r != null && IsCustomType(r, null, null); }
                    default: return false;
                }
            }

            private static string TypeSigChar(Il2CppType t, bool byref)
            {
                if (byref) return "i";
                switch (t.Type)
                {
                    case Il2CppTypeEnum.IL2CPP_TYPE_VOID: return "v";
                    case Il2CppTypeEnum.IL2CPP_TYPE_I8:
                    case Il2CppTypeEnum.IL2CPP_TYPE_U8: return "j";
                    case Il2CppTypeEnum.IL2CPP_TYPE_R4: return "f";
                    case Il2CppTypeEnum.IL2CPP_TYPE_R8: return "d";
                    default: return "i";
                }
            }

            private void BuildSignature(ScriptMethod sm, Il2CppMethodDefinition m, Il2CppTypeDefinition declaring, Il2CppGenericInst classInst, Il2CppGenericInst methodInst)
            {
                var sig = new StringBuilder();
                var tsig = new StringBuilder();
                string ret;
                try
                {
                    var rt = m.RawReturnType;
                    ret = ParseType(rt, classInst, methodInst) + (rt.Byref != 0 ? "*" : "");
                    tsig.Append(TypeSigChar(rt, rt.Byref != 0));
                }
                catch
                {
                    ret = "void*";
                    tsig.Append('i');
                }
                var ps = new List<string>();
                if (!m.IsStatic)
                {
                    var thisName = structNameDic.TryGetValue(declaring, out var sn) ? sn : "Il2CppObject";
                    ps.Add((declaring.IsValueType ? thisName + "_o*" : thisName + "_o*") + " __this");
                    tsig.Append('i');
                }
                else if (mv <= 24)
                {
                    ps.Add("Il2CppObject* __this");
                    tsig.Append('i');
                }
                Il2CppParameterReflectionData[] pars = null;
                try { pars = m.Parameters; } catch { /* ignore */ }
                var i = 0;
                foreach (var p in pars ?? Array.Empty<Il2CppParameterReflectionData>())
                {
                    string ct;
                    var byref = false;
                    try
                    {
                        byref = p.RawType.Byref != 0;
                        ct = ParseType(p.RawType, classInst, methodInst) + (byref ? "*" : "");
                        tsig.Append(TypeSigChar(p.RawType, byref));
                    }
                    catch
                    {
                        ct = "void*";
                        tsig.Append('i');
                    }
                    var pname = string.IsNullOrEmpty(p.ParameterName) ? "p" + i : p.ParameterName;
                    ps.Add(ct + " " + FixName(pname));
                    i++;
                }
                ps.Add("const MethodInfo* method");
                tsig.Append('i');
                sig.Append(ret).Append(' ').Append(FixName(sm.Name)).Append(" (").Append(string.Join(", ", ps)).Append(");");
                sm.Signature = sig.ToString();
                sm.TypeSignature = tsig.ToString();
            }

            #endregion

            #region structs

            private void AddStruct(Il2CppTypeDefinition td)
            {
                var si = new StructInfo { TypeName = structNameDic[td], IsValueType = td.IsValueType };
                Fill(si, td, null);
                Register(si);
            }

            private void AddGenericStruct(string name, Il2CppTypeDefinition td, Il2CppGenericInst inst)
            {
                var si = new StructInfo { TypeName = name, IsValueType = td.IsValueType };
                Fill(si, td, inst);
                Register(si);
            }

            private void Register(StructInfo si)
            {
                structList.Add(si);
                structByName[si.TypeName + "_o"] = si;
            }

            private void Fill(StructInfo si, Il2CppTypeDefinition td, Il2CppGenericInst inst)
            {
                // parent
                if (!td.IsValueType && !td.IsEnumType)
                {
                    try
                    {
                        var parent = td.RawBaseType;
                        if (parent != null && parent.Type != Il2CppTypeEnum.IL2CPP_TYPE_OBJECT)
                            si.Parent = StructName(parent, inst, null);
                    }
                    catch { /* ignore */ }
                }
                // fields
                var seen = new HashSet<string>(StringComparer.Ordinal);
                Il2CppFieldReflectionData[] fields = null;
                try { fields = td.FieldInfos; } catch { /* ignore */ }
                var idx = 0;
                foreach (var f in fields ?? Array.Empty<Il2CppFieldReflectionData>())
                {
                    idx++;
                    if ((f.Attributes & System.Reflection.FieldAttributes.Literal) != 0) continue;
                    var ft = f.Field.RawFieldType;
                    string ctype;
                    bool isVt, isCustom;
                    try
                    {
                        ctype = ParseType(ft, inst, null);
                        isVt = IsValueTypeStruct(ft, inst, null);
                        isCustom = IsCustomType(ft, inst, null);
                    }
                    catch
                    {
                        ctype = "void*"; isVt = false; isCustom = false;
                    }
                    var name = FixName(f.Field.Name);
                    if (!seen.Add(name)) name = $"_{idx}_{name}";
                    var entry = (ctype, name, isVt, isCustom);
                    if ((f.Attributes & System.Reflection.FieldAttributes.Static) != 0) si.StaticFields.Add(entry);
                    else si.Fields.Add(entry);
                }
                // vtable
                try
                {
                    var vt = td.VTable;
                    if (vt != null && vt.Length > 0)
                    {
                        var slots = new SortedDictionary<int, string>();
                        foreach (var u in vt)
                        {
                            if (u == null) continue;
                            Il2CppMethodDefinition mdef = null;
                            try
                            {
                                if (u.Type == MetadataUsageType.MethodDef) mdef = u.AsMethod();
                                else if (u.Type == MetadataUsageType.MethodRef) mdef = u.AsGenericMethodRef()?.BaseMethod;
                            }
                            catch { /* ignore */ }
                            if (mdef == null || mdef.slot == ushort.MaxValue) continue;
                            slots[mdef.slot] = FixName(mdef.Name);
                        }
                        if (slots.Count > 0)
                        {
                            si.VTable = new string[slots.Keys.Last() + 1];
                            foreach (var kv in slots) si.VTable[kv.Key] = kv.Value;
                        }
                    }
                }
                catch { /* ignore */ }
            }

            private string Emit(StructInfo si)
            {
                if (!emitted.Add(si)) return "";
                var pre = new StringBuilder();
                var sb = new StringBuilder();
                if (si.Parent != null && structByName.TryGetValue(si.Parent + "_o", out var parentInfo))
                {
                    pre.Append(Emit(parentInfo));
                    sb.Append("struct ").Append(si.TypeName).Append("_Fields : ").Append(si.Parent).Append("_Fields {\n");
                }
                else
                {
                    sb.Append("struct ").Append(si.TypeName).Append("_Fields {\n");
                }
                foreach (var f in si.Fields)
                {
                    if (f.isValueType && structByName.TryGetValue(f.type, out var fi)) pre.Append(Emit(fi));
                    sb.Append('\t').Append(f.isCustom ? "struct " : "").Append(f.type).Append(' ').Append(f.name).Append(";\n");
                }
                sb.Append("};\n");

                if (si.VTable.Length > 0)
                {
                    sb.Append("struct ").Append(si.TypeName).Append("_VTable {\n");
                    for (var i = 0; i < si.VTable.Length; i++)
                        sb.Append("\tVirtualInvokeData _").Append(i).Append('_').Append(si.VTable[i] ?? "unknown").Append(";\n");
                    sb.Append("};\n");
                }

                sb.Append("struct ").Append(si.TypeName).Append("_c {\n\tIl2CppClass_1 _1;\n");
                sb.Append(si.StaticFields.Count > 0 ? "\tstruct " + si.TypeName + "_StaticFields* static_fields;\n" : "\tvoid* static_fields;\n");
                sb.Append("\tIl2CppRGCTXData* rgctx_data;\n\tIl2CppClass_2 _2;\n");
                sb.Append(si.VTable.Length > 0 ? "\t" + si.TypeName + "_VTable vtable;\n" : "\tVirtualInvokeData vtable[32];\n");
                sb.Append("};\n");

                sb.Append("struct ").Append(si.TypeName).Append("_o {\n");
                if (!si.IsValueType)
                    sb.Append('\t').Append(si.TypeName).Append("_c *klass;\n\tvoid *monitor;\n");
                sb.Append('\t').Append(si.TypeName).Append("_Fields fields;\n};\n");

                if (si.StaticFields.Count > 0)
                {
                    sb.Append("struct ").Append(si.TypeName).Append("_StaticFields {\n");
                    foreach (var f in si.StaticFields)
                    {
                        if (f.isValueType && structByName.TryGetValue(f.type, out var fi)) pre.Append(Emit(fi));
                        sb.Append('\t').Append(f.isCustom ? "struct " : "").Append(f.type).Append(' ').Append(f.name).Append(";\n");
                    }
                    sb.Append("};\n");
                }
                return pre.Append(sb).ToString();
            }

            #endregion

            #region metadata usages

            private IEnumerable<MetadataUsage> EnumerateMetadataUsages()
            {
                // Pre-27 binaries: LibCpp2IL fills its global lists eagerly.
                var fromLists = new List<MetadataUsage>();
                foreach (var listName in new[] { "TypeRefs", "MethodRefs", "FieldRefs", "Literals" })
                {
                    var f = typeof(LibCpp2IlGlobalMapper).GetField(listName, BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static);
                    if (f?.GetValue(null) is List<MetadataUsage> list) fromLists.AddRange(list);
                }
                if (fromLists.Count > 0)
                    return fromLists;

                // v27+: usages are encoded in the binary; scan data sections only (Il2CppDumper's
                // approach). Walking the whole file is far too slow on large GameAssembly.dlls.
                var ranges = DataSectionRanges();
                if (ranges.Count == 0)
                {
                    log?.Invoke("[il2cpp] No PE/ELF data sections found; skipping metadata-usage scan (methods/structs are still written).");
                    return Array.Empty<MetadataUsage>();
                }
                var result = new List<MetadataUsage>();
                var seenAddr = new HashSet<ulong>();
                var step = (ulong)PointerSize();
                var scanned = 0;
                foreach (var (vaStart, size) in ranges)
                {
                    var end = vaStart + size;
                    for (var va = vaStart; va + step <= end; va += step)
                    {
                        scanned++;
                        MetadataUsage u;
                        try { u = LibCpp2IlGlobalMapper.CheckForPost27GlobalAt(va); }
                        catch { continue; }
                        if (u == null || !u.IsValid) continue;
                        if (seenAddr.Add(u.Offset != 0 ? u.Offset : va)) result.Add(u);
                    }
                }
                log?.Invoke($"[il2cpp] Metadata-usage scan: {result.Count} hits over {ranges.Count} data section(s) ({scanned} pointers).");
                return result;
            }

            /// <summary>Virtual-address ranges of initialized/writable non-executable sections (PE .rdata/.data, ELF PT_LOAD without PF_X).</summary>
            private List<(ulong va, ulong size)> DataSectionRanges()
            {
                try
                {
                    if (!string.IsNullOrEmpty(binaryPath) && File.Exists(binaryPath))
                    {
                        using (var fs = File.OpenRead(binaryPath))
                        using (var br = new BinaryReader(fs))
                        {
                            var mag = br.ReadUInt16();
                            fs.Position = 0;
                            if (mag == 0x5A4D) return PeDataSections(br);
                            if (mag == 0x457F) return ElfDataSections(br); // 0x7F 'E' little-endian as UInt16 = 0x457F
                        }
                    }
                }
                catch (Exception ex)
                {
                    log?.Invoke($"[il2cpp] Could not parse data sections: {ex.Message}");
                }
                return new List<(ulong, ulong)>();
            }

            private static List<(ulong va, ulong size)> PeDataSections(BinaryReader br)
            {
                var fs = br.BaseStream;
                fs.Position = 0x3C;
                var lfanew = br.ReadInt32();
                fs.Position = lfanew;
                if (br.ReadUInt32() != 0x4550) return new List<(ulong, ulong)>();
                br.ReadUInt16(); // Machine
                var numSections = br.ReadUInt16();
                fs.Position += 12; // TimeDateStamp + PointerToSymbolTable + NumberOfSymbols
                var optSize = br.ReadUInt16();
                br.ReadUInt16(); // Characteristics
                var optStart = fs.Position;
                var magic = br.ReadUInt16();
                ulong imageBase;
                if (magic == 0x20B)
                {
                    fs.Position = optStart + 24;
                    imageBase = br.ReadUInt64();
                }
                else if (magic == 0x10B)
                {
                    fs.Position = optStart + 28;
                    imageBase = br.ReadUInt32();
                }
                else return new List<(ulong, ulong)>();
                fs.Position = optStart + optSize;
                const uint MemExecute = 0x20000000;
                const uint CntCode = 0x00000020;
                const uint CntInitData = 0x00000040;
                var ranges = new List<(ulong, ulong)>();
                for (var i = 0; i < numSections; i++)
                {
                    fs.Position += 8; // Name
                    var virtualSize = br.ReadUInt32();
                    var virtualAddress = br.ReadUInt32();
                    var sizeOfRaw = br.ReadUInt32();
                    fs.Position += 16; // PointerToRawData through NumberOfLineNumbers
                    var characteristics = br.ReadUInt32();
                    if ((characteristics & (MemExecute | CntCode)) != 0) continue;
                    if ((characteristics & CntInitData) == 0) continue;
                    var size = Math.Max(virtualSize, sizeOfRaw);
                    if (size == 0) continue;
                    ranges.Add((imageBase + virtualAddress, size));
                }
                return ranges;
            }

            private static List<(ulong va, ulong size)> ElfDataSections(BinaryReader br)
            {
                var fs = br.BaseStream;
                var ident = br.ReadBytes(16);
                if (ident.Length < 16 || ident[0] != 0x7F || ident[1] != (byte)'E') return new List<(ulong, ulong)>();
                var is64 = ident[4] == 2;
                var little = ident[5] != 2;
                if (!little) return new List<(ulong, ulong)>(); // uncommon for Unity
                br.ReadUInt16(); // e_type
                br.ReadUInt16(); // e_machine
                br.ReadUInt32(); // e_version
                ulong e_phoff;
                if (is64)
                {
                    br.ReadUInt64(); // e_entry
                    e_phoff = br.ReadUInt64();
                    br.ReadUInt64(); // e_shoff
                }
                else
                {
                    br.ReadUInt32();
                    e_phoff = br.ReadUInt32();
                    br.ReadUInt32();
                }
                br.ReadUInt32(); // e_flags
                br.ReadUInt16(); // e_ehsize
                var e_phentsize = br.ReadUInt16();
                var e_phnum = br.ReadUInt16();
                const int PT_LOAD = 1;
                const int PF_X = 1;
                var ranges = new List<(ulong, ulong)>();
                for (var i = 0; i < e_phnum; i++)
                {
                    fs.Position = (long)e_phoff + i * e_phentsize;
                    uint p_type;
                    ulong p_vaddr, p_memsz;
                    uint p_flags;
                    if (is64)
                    {
                        p_type = br.ReadUInt32();
                        p_flags = br.ReadUInt32();
                        br.ReadUInt64(); // p_offset
                        p_vaddr = br.ReadUInt64();
                        br.ReadUInt64(); // p_paddr
                        br.ReadUInt64(); // p_filesz
                        p_memsz = br.ReadUInt64();
                    }
                    else
                    {
                        p_type = br.ReadUInt32();
                        br.ReadUInt32(); // p_offset
                        p_vaddr = br.ReadUInt32();
                        br.ReadUInt32(); // p_paddr
                        br.ReadUInt32(); // p_filesz
                        p_memsz = br.ReadUInt32();
                        p_flags = br.ReadUInt32();
                    }
                    if (p_type != PT_LOAD || (p_flags & PF_X) != 0 || p_memsz == 0) continue;
                    ranges.Add((p_vaddr, p_memsz));
                }
                return ranges;
            }

            private void AddUsage(ScriptJson json, MetadataUsage u)
            {
                ulong rva;
                try { rva = bin.GetRva(u.Offset); } catch { return; }
                try
                {
                    switch (u.Type)
                    {
                        case MetadataUsageType.TypeInfo:
                            {
                                var r = u.AsType();
                                var name = DisplayName(r);
                                var sn = StructName(r);
                                json.ScriptMetadata.Add(new ScriptMetadata { Address = rva, Name = name + "_TypeInfo", Signature = sn.EndsWith("_array") ? "Il2CppClass*" : sn + "_c*" });
                                break;
                            }
                        case MetadataUsageType.Type:
                            json.ScriptMetadata.Add(new ScriptMetadata { Address = rva, Name = DisplayName(u.AsType()) + "_var", Signature = "Il2CppType*" });
                            break;
                        case MetadataUsageType.MethodDef:
                            {
                                var m = u.AsMethod();
                                json.ScriptMetadataMethod.Add(new ScriptMetadataMethod
                                {
                                    Address = rva,
                                    Name = "Method$" + TypeDefDisplayName(m.DeclaringType) + "." + m.Name + "()",
                                    MethodAddress = m.MethodPointer != 0 ? bin.GetRva(m.MethodPointer) : 0,
                                });
                                break;
                            }
                        case MetadataUsageType.MethodRef:
                            {
                                var r = u.AsGenericMethodRef();
                                ulong maddr = 0;
                                if (r.GenericVariantPtr != 0) maddr = bin.GetRva(r.GenericVariantPtr);
                                json.ScriptMetadataMethod.Add(new ScriptMetadataMethod
                                {
                                    Address = rva,
                                    Name = "Method$" + TypeDefDisplayName(r.DeclaringType) + GenericArgs(r.TypeGenericParams) + "." + r.BaseMethod.Name + GenericArgs(r.MethodGenericParams) + "()",
                                    MethodAddress = maddr,
                                });
                                break;
                            }
                        case MetadataUsageType.FieldInfo:
                            {
                                var f = u.AsField();
                                json.ScriptMetadata.Add(new ScriptMetadata { Address = rva, Name = "Field$" + TypeDefDisplayName(f.DeclaringType) + "." + f.Name });
                                break;
                            }
                        case MetadataUsageType.StringLiteral:
                            json.ScriptString.Add(new ScriptString { Address = rva, Value = u.AsLiteral() ?? "" });
                            break;
                    }
                }
                catch (Exception ex)
                {
                    log?.Invoke($"[il2cpp] usage {u.Type} at 0x{u.Offset:X}: {ex.Message}");
                }
            }

            private string StructName(Il2CppTypeReflectionData r)
            {
                if (r == null) return "System_Object";
                if (r.isArray)
                {
                    var elem = StructName(r.arrayType);
                    var name = elem + "_array";
                    if (arrayNames.Add(name))
                        arrayHeader.Append("struct ").Append(name).Append(" {\n\tIl2CppObject obj;\n\tIl2CppArrayBounds *bounds;\n\til2cpp_array_size_t max_length;\n\t")
                            .Append(ElemCType(r.arrayType)).Append(" m_Items[65535];\n};\n");
                    return name;
                }
                if (!r.isType || r.baseType == null) return "System_Object";
                if (r.isGenericType && r.genericParams != null && r.genericParams.Length > 0)
                {
                    var key = FixName(StripArity(structNameDic.TryGetValue(r.baseType, out var bn) ? bn : TypeDefDisplayName(r.baseType)))
                              + "_" + string.Join("_", r.genericParams.Select(p => FixName(DisplayName(p)))) + "_";
                    if (!genericStructNames.TryGetValue(key, out var name))
                    {
                        name = Unique(key);
                        genericStructNames[key] = name;
                        pendingGenerics[name] = (r.baseType, null); // no Il2CppGenericInst available here: emit with open generic params
                    }
                    return name;
                }
                return structNameDic.TryGetValue(r.baseType, out var n) ? n : "System_Object";
            }

            private string ElemCType(Il2CppTypeReflectionData r)
            {
                if (r == null || !r.isType || r.baseType == null) return r != null && r.isArray ? StructName(r) + "*" : "Il2CppObject*";
                var td = r.baseType;
                if (td.IsEnumType && td.EnumUnderlyingType != null) return ParseType(td.EnumUnderlyingType, null, null);
                if (td.IsValueType) return StructName(r) + "_o";
                return StructName(r) + "_o*";
            }

            #endregion
        }

        #endregion
    }
}
#endif
