using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

namespace UnityRift
{
    /// <summary>
    /// Generates a ready-to-run Frida script that hooks IL2CPP methods by their RVA and logs typed
    /// args/return, so a static finding (a method + its managed signature) can be confirmed dynamically
    /// at runtime. The script resolves the module base itself (survives ASLR), handles ARM Thumb
    /// (adds the +1 for <c>Interceptor.attach</c>), and decodes <c>System.String</c> args.
    /// </summary>
    public static class Il2CppFridaGenerator
    {
        public struct Hook { public string Name; public ulong Rva; public string Signature; public bool Thumb; }

        private static readonly Regex ParamSplit = new Regex(@",(?![^<]*>)", RegexOptions.Compiled);

        /// <summary>Counts the native argument slots of a package method signature (includes __this and the trailing MethodInfo*).</summary>
        public static int ArgCount(string signature) => Params(signature).Count;

        /// <summary>Parsed (cType, name) parameters from a package method prototype.</summary>
        private static List<(string type, string name)> Params(string signature)
        {
            var list = new List<(string, string)>();
            if (string.IsNullOrEmpty(signature)) return list;
            var open = signature.IndexOf('(');
            var close = signature.LastIndexOf(')');
            if (open < 0 || close <= open) return list;
            var inner = signature.Substring(open + 1, close - open - 1).Trim();
            if (inner.Length == 0 || inner == "void") return list;
            foreach (var p in ParamSplit.Split(inner))
            {
                var t = p.Trim();
                if (t.Length == 0) continue;
                var sp = t.LastIndexOf(' ');
                if (sp <= 0) { list.Add((t, "a" + list.Count)); continue; }
                list.Add((t.Substring(0, sp).Trim(), t.Substring(sp + 1).Trim().TrimStart('*')));
            }
            return list;
        }

        private static bool IsFloat(string t) => t == "float" || t == "double";
        private static bool IsString(string t) => t.Contains("System_String_o");

        public static string Generate(string moduleName, IEnumerable<Hook> hooks)
        {
            var sb = new StringBuilder();
            sb.Append("// Frida hooks generated by UnityRift. Run: frida -U -f <package> -l this.js --no-pause\n");
            sb.Append("// (or: frida -U <process> -l this.js). Integer/pointer args are logged; String args are decoded.\n\n");
            sb.Append("const MODULE = ").Append(JsString(moduleName)).Append(";\n");
            sb.Append(@"function moduleBase() {
  const m = Process.findModuleByName(MODULE);
  if (!m) throw new Error('module not loaded yet: ' + MODULE);
  return m.base;
}

// Read an IL2CPP System.String* (object header + length + UTF-16 chars).
function readStr(p) {
  try {
    p = ptr(p);
    if (p.isNull()) return 'null';
    const wide = Process.pointerSize === 8;
    const len = p.add(wide ? 0x10 : 0x8).readS32();
    if (len < 0 || len > 0x10000) return p.toString();
    return JSON.stringify(p.add(wide ? 0x14 : 0xC).readUtf16String(len));
  } catch (e) { return ptr(p).toString(); }
}

// addr = module base + rva (+1 for ARM Thumb, so Interceptor lands on the right mode).
function at(rva, thumb) { const a = moduleBase().add(rva); return thumb ? a.or(1) : a; }

");
            foreach (var h in hooks)
            {
                var ps = Params(h.Signature);
                var hasFp = ps.Any(p => IsFloat(p.type));
                sb.Append("// ").Append(h.Signature ?? "").Append('\n');
                if (h.Thumb) sb.Append("// (ARM Thumb)\n");
                sb.Append("Interceptor.attach(at(ptr('0x").Append(h.Rva.ToString("X")).Append("'), ")
                  .Append(h.Thumb ? "true" : "false").Append("), {\n");
                sb.Append("  onEnter(args) {\n");
                sb.Append("    console.log(").Append(JsString("[>] " + (h.Name ?? "?"))).Append(");\n");
                if (hasFp)
                    sb.Append("    // note: this method has float/double params — those travel in FP registers,\n    // not in args[]; the arg indices below cover only integer/pointer params.\n");
                var idx = 0;
                foreach (var p in ps)
                {
                    // On AArch64 float params use a separate register bank and don't consume an args[] slot.
                    if (IsFloat(p.type)) continue;
                    var label = p.name + " (" + p.type + ")";
                    if (IsString(p.type))
                        sb.Append("    console.log('    ").Append(JsEsc(label)).Append(" = ' + readStr(args[").Append(idx).Append("]));\n");
                    else
                        sb.Append("    console.log('    ").Append(JsEsc(label)).Append(" = ' + args[").Append(idx).Append("]);\n");
                    idx++;
                }
                sb.Append("    this.name = ").Append(JsString(h.Name ?? "?")).Append(";\n");
                sb.Append("  },\n");
                sb.Append("  onLeave(ret) { console.log('[<] ' + this.name + ' = ' + ret); }\n");
                sb.Append("});\n");
                sb.Append("console.log('hooked ").Append(JsEsc(h.Name ?? "?")).Append(" @ 0x").Append(h.Rva.ToString("X")).Append("');\n\n");
            }
            return sb.ToString();
        }

        private static string JsString(string s) => "'" + JsEsc(s) + "'";
        private static string JsEsc(string s) => (s ?? "").Replace("\\", "\\\\").Replace("'", "\\'");
    }
}
