using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace UnityRift
{
    /// <summary>
    /// Generates a ready-to-run Frida script that hooks IL2CPP methods by their RVA and logs typed
    /// args/return, so a static finding (a method + its managed signature) can be confirmed dynamically
    /// at runtime. The script resolves the module base itself, so it survives ASLR.
    /// </summary>
    public static class Il2CppFridaGenerator
    {
        public struct Hook { public string Name; public ulong Rva; public string Signature; }

        /// <summary>Counts the native argument slots of a package method signature (includes __this and the trailing MethodInfo*).</summary>
        public static int ArgCount(string signature)
        {
            if (string.IsNullOrEmpty(signature)) return 0;
            var open = signature.IndexOf('(');
            var close = signature.LastIndexOf(')');
            if (open < 0 || close <= open) return 0;
            var inner = signature.Substring(open + 1, close - open - 1).Trim();
            if (inner.Length == 0 || inner == "void") return 0;
            // split on top-level commas (parameters have no nested commas in these C prototypes)
            return inner.Split(',').Count(p => p.Trim().Length > 0);
        }

        public static string Generate(string moduleName, IEnumerable<Hook> hooks)
        {
            var sb = new StringBuilder();
            sb.Append("// Frida hooks generated by UnityRift. Run: frida -U -f <package> -l this.js --no-pause\n");
            sb.Append("// (or: frida -U <process> -l this.js). Args/return are logged as raw pointers;\n");
            sb.Append("// use readStr(p) on a System.String* arg to print its text.\n\n");
            sb.Append("const MODULE = ").Append(JsString(moduleName)).Append(";\n");
            sb.Append(@"function moduleBase() {
  let m = Process.findModuleByName(MODULE);
  if (!m) throw new Error('module not loaded yet: ' + MODULE);
  return m.base;
}

// Read an IL2CPP System.String* (object header + length + UTF-16 chars).
function readStr(p) {
  try {
    p = ptr(p);
    if (p.isNull()) return 'null';
    const len = p.add(Process.pointerSize === 8 ? 0x10 : 0x8).readS32();
    if (len < 0 || len > 0x10000) return p.toString();
    return p.add(Process.pointerSize === 8 ? 0x14 : 0xC).readUtf16String(len);
  } catch (e) { return p.toString(); }
}

function hook(rva, label, argc, sig) {
  const addr = moduleBase().add(rva);
  Interceptor.attach(addr, {
    onEnter(args) {
      this.label = label;
      const shown = [];
      for (let i = 0; i < argc; i++) shown.push(args[i]);
      console.log('[>] ' + label + '(' + shown.map(String).join(', ') + ')');
    },
    onLeave(ret) {
      console.log('[<] ' + this.label + ' = ' + ret);
    }
  });
  console.log('hooked ' + label + ' @ ' + addr);
}

");
            foreach (var h in hooks)
            {
                sb.Append("// ").Append(h.Signature ?? "").Append('\n');
                sb.Append("hook(ptr('0x").Append(h.Rva.ToString("X")).Append("'), ")
                  .Append(JsString(h.Name)).Append(", ")
                  .Append(ArgCount(h.Signature)).Append(", ")
                  .Append(JsString(h.Signature ?? "")).Append(");\n\n");
            }
            return sb.ToString();
        }

        private static string JsString(string s) => "'" + (s ?? "").Replace("\\", "\\\\").Replace("'", "\\'") + "'";
    }
}
