using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

namespace UnityRift
{
    /// <summary>
    /// Converts a Unity <see cref="Material"/> (and, when available, its <see cref="Shader"/>) into a
    /// Godot 4 material scaffold: a <c>.gdshader</c> (shader_type spatial) with render_mode + uniforms
    /// derived from the Unity render states and properties, and a <c>.tres</c> ShaderMaterial that binds
    /// the saved property values and textures. The pixel logic still needs hand-porting (embedded as a
    /// reference block), but blend/cull/depth, uniforms, defaults, texture slots and a best-effort
    /// albedo/tint/metallic/roughness body are produced automatically.
    /// </summary>
    public static class GodotMaterialExporter
    {
        public sealed class Result
        {
            public string ShaderName;      // sanitized base name (no extension)
            public string GdShader;        // .gdshader text
            public string Tres;            // .tres text
            public string ShaderReference; // original Unity shader dump (ShaderLab + GLSL/SPIR-V asm), or null
        }

        // Unity UnityEngine.Rendering.BlendMode
        private enum UBlend { Zero = 0, One = 1, DstColor = 2, SrcColor = 3, OneMinusDstColor = 4, SrcAlpha = 5, OneMinusSrcColor = 6, DstAlpha = 7, OneMinusDstAlpha = 8, SrcAlphaSaturate = 9, OneMinusSrcAlpha = 10 }
        // Unity UnityEngine.Rendering.CullMode
        private enum UCull { Off = 0, Front = 1, Back = 2 }
        // Unity UnityEngine.Rendering.CompareFunction
        private enum UCompare { Disabled = 0, Never = 1, Less = 2, Equal = 3, LessEqual = 4, Greater = 5, NotEqual = 6, GreaterEqual = 7, Always = 8 }

        /// <param name="mat">Material to convert.</param>
        /// <param name="shader">Resolved shader, or null when stripped/unavailable.</param>
        /// <param name="texEnvResPaths">
        /// Map from texture property name (e.g. "_MainTex") to a Godot res:// path for the exported
        /// texture (e.g. "res://textures/foo.png"), or null/empty when the texture was not exported.
        /// </param>
        public static Result Export(Material mat, Shader shader, IDictionary<string, string> texEnvResPaths)
        {
            texEnvResPaths ??= new Dictionary<string, string>();
            var name = Sanitize(string.IsNullOrEmpty(mat.m_Name) ? "material" : mat.m_Name);

            var props = mat.m_SavedProperties;
            var texEnvs = props?.m_TexEnvs ?? new List<KeyValuePair<string, UnityTexEnv>>();
            var floats = props?.m_Floats ?? new List<KeyValuePair<string, float>>();
            var colors = props?.m_Colors ?? new List<KeyValuePair<string, Color>>();
            var ints = props?.m_Ints ?? new List<KeyValuePair<string, int>>();

            // ---- Property type map from the shader definition (falls back to saved-property kinds) ----
            var declared = new Dictionary<string, SerializedPropertyType>();
            SerializedShaderState firstState = null;
            string unityShaderName = shader?.m_ParsedForm?.m_Name ?? mat.m_Shader.Name;
            var keywords = new List<string>();
            if (shader?.m_ParsedForm != null)
            {
                if (shader.m_ParsedForm.m_PropInfo?.m_Props != null)
                    foreach (var p in shader.m_ParsedForm.m_PropInfo.m_Props)
                        declared[p.m_Name] = p.m_Type;
                firstState = shader.m_ParsedForm.m_SubShaders?
                    .FirstOrDefault()?.m_Passes?
                    .FirstOrDefault(p => p.m_State != null)?.m_State;
            }

            // ================= .gdshader =================
            var gd = new StringBuilder();
            gd.Append("// Godot 4 shader scaffold generated by UnityRift from Unity material \"")
              .Append(mat.m_Name).Append("\".\n");
            if (!string.IsNullOrEmpty(unityShaderName))
                gd.Append("// Source Unity shader: ").Append(unityShaderName).Append('\n');
            gd.Append("// NOTE: render_mode, uniforms and defaults are mapped automatically; the fragment()\n");
            gd.Append("//       body is a best-effort starting point. Port the real pixel logic by hand.\n\n");
            gd.Append("shader_type spatial;\n");
            gd.Append("render_mode ").Append(BuildRenderMode(firstState, out bool transparent)).Append(";\n\n");

            // Uniforms. Prefer declared shader props; add any saved property not declared.
            var emitted = new HashSet<string>(StringComparer.Ordinal);
            var uniformNames = new Dictionary<string, string>(StringComparer.Ordinal); // unityName -> godot uniform id

            // textures first
            foreach (var te in texEnvs)
            {
                var uName = te.Key;
                if (!emitted.Add(uName)) continue;
                var gName = SanitizeIdent(uName);
                uniformNames[uName] = gName;
                gd.Append("uniform sampler2D ").Append(gName);
                var hint = TextureHint(uName);
                if (hint != null) gd.Append(" : ").Append(hint);
                gd.Append(";\n");
            }
            // Classify each vec4 property as a color (source_color hint) or a plain vector.
            var colorIsColor = new Dictionary<string, bool>(StringComparer.Ordinal);
            foreach (var c in colors)
                colorIsColor[c.Key] = IsColorProp(c.Key, c.Value, declared);
            foreach (var c in colors)
            {
                if (!emitted.Add(c.Key)) continue;
                var gName = SanitizeIdent(c.Key);
                uniformNames[c.Key] = gName;
                if (colorIsColor[c.Key])
                    gd.Append("uniform vec4 ").Append(gName).Append(" : source_color = ")
                      .Append(Vec4(c.Value.R, c.Value.G, c.Value.B, c.Value.A)).Append(";\n");
                else
                    gd.Append("uniform vec4 ").Append(gName).Append(" = ")
                      .Append(Vec4(c.Value.R, c.Value.G, c.Value.B, c.Value.A)).Append(";\n");
            }
            foreach (var f in floats)
            {
                if (!emitted.Add(f.Key)) continue;
                var gName = SanitizeIdent(f.Key);
                uniformNames[f.Key] = gName;
                var isRange = declared.TryGetValue(f.Key, out var t) && t == SerializedPropertyType.Range;
                gd.Append("uniform float ").Append(gName);
                if (isRange) gd.Append(" : hint_range(0.0, 1.0)");
                gd.Append(" = ").Append(F(f.Value)).Append(";\n");
            }
            foreach (var i in ints)
            {
                if (!emitted.Add(i.Key)) continue;
                var gName = SanitizeIdent(i.Key);
                uniformNames[i.Key] = gName;
                gd.Append("uniform int ").Append(gName).Append(" = ").Append(i.Value.ToString(CultureInfo.InvariantCulture)).Append(";\n");
            }

            // Best-effort fragment body
            gd.Append('\n');
            gd.Append(BuildFragment(uniformNames, texEnvs, colors, floats, transparent));

            // Reference: the extracted GPU program(s) go to a separate sidecar file (kept out of the
            // .gdshader so the shader stays clean and the reference stays portable). For SPIR-V builds
            // this sidecar carries the SPIR-V assembly; for GL builds, the GLSL; for DX builds, a note.
            string shaderReference = null;
            if (shader != null)
            {
                string dump;
                try { dump = shader.Convert(); }
                catch (Exception e) { dump = "// shader convert failed: " + e.Message; }
                shaderReference =
                    $"// Original Unity shader \"{unityShaderName}\" (ShaderLab + GPU programs).\n" +
                    "// Port the logic into the fragment() of " + name + ".gdshader.\n\n" + dump;
                gd.Append("\n// Original shader body: see \"").Append(name).Append(".shaderref.txt\" (ShaderLab + GLSL/SPIR-V).\n");
            }
            else
            {
                gd.Append("\n// Shader asset not available (stripped or in another bundle);\n");
                gd.Append("// only the material's properties/render states were recovered.\n");
            }

            // ================= .tres =================
            var tres = BuildTres(name, mat, uniformNames, texEnvs, colors, floats, ints, texEnvResPaths, colorIsColor);

            return new Result { ShaderName = name, GdShader = gd.ToString(), Tres = tres, ShaderReference = shaderReference };
        }

        private static string BuildTres(string name, Material mat,
            Dictionary<string, string> uniformNames,
            List<KeyValuePair<string, UnityTexEnv>> texEnvs,
            List<KeyValuePair<string, Color>> colors,
            List<KeyValuePair<string, float>> floats,
            List<KeyValuePair<string, int>> ints,
            IDictionary<string, string> texEnvResPaths,
            Dictionary<string, bool> colorIsColor)
        {
            // ext_resources: the shader + each exported texture
            var ext = new StringBuilder();
            var body = new StringBuilder();
            int id = 1;
            var shaderId = id++;
            ext.Append("[ext_resource type=\"Shader\" path=\"res://").Append(name).Append(".gdshader\" id=\"")
               .Append(shaderId).Append("\"]\n");

            var texIds = new Dictionary<string, int>(StringComparer.Ordinal);
            foreach (var te in texEnvs)
            {
                if (!texEnvResPaths.TryGetValue(te.Key, out var res) || string.IsNullOrEmpty(res))
                    continue;
                var tid = id++;
                texIds[te.Key] = tid;
                ext.Append("[ext_resource type=\"Texture2D\" path=\"").Append(res).Append("\" id=\"").Append(tid).Append("\"]\n");
            }

            body.Append("[resource]\n");
            body.Append("shader = ExtResource(\"").Append(shaderId).Append("\")\n");
            foreach (var c in colors)
            {
                var isColor = colorIsColor != null && colorIsColor.TryGetValue(c.Key, out var b) && b;
                var ctor = isColor ? "Color(" : "Vector4(";
                body.Append("shader_parameter/").Append(SanitizeIdent(c.Key)).Append(" = ").Append(ctor)
                    .Append(F(c.Value.R)).Append(", ").Append(F(c.Value.G)).Append(", ")
                    .Append(F(c.Value.B)).Append(", ").Append(F(c.Value.A)).Append(")\n");
            }
            foreach (var f in floats)
                body.Append("shader_parameter/").Append(SanitizeIdent(f.Key)).Append(" = ").Append(F(f.Value)).Append('\n');
            foreach (var i in ints)
                body.Append("shader_parameter/").Append(SanitizeIdent(i.Key)).Append(" = ").Append(i.Value.ToString(CultureInfo.InvariantCulture)).Append('\n');
            foreach (var te in texEnvs)
                if (texIds.TryGetValue(te.Key, out var tid))
                    body.Append("shader_parameter/").Append(SanitizeIdent(te.Key)).Append(" = ExtResource(\"").Append(tid).Append("\")\n");

            var loadSteps = id; // ext resources + 1
            var sb = new StringBuilder();
            sb.Append("[gd_resource type=\"ShaderMaterial\" load_steps=").Append(loadSteps).Append(" format=3]\n\n");
            sb.Append(ext).Append('\n');
            sb.Append(body);
            return sb.ToString();
        }

        private static string BuildRenderMode(SerializedShaderState st, out bool transparent)
        {
            transparent = false;
            var parts = new List<string>();
            // Blend
            if (st != null && st.rtBlend != null && st.rtBlend.Length > 0)
            {
                var b = st.rtBlend[0];
                var src = (UBlend)(int)b.srcBlend.val;
                var dst = (UBlend)(int)b.destBlend.val;
                if (!(src == UBlend.One && dst == UBlend.Zero)) // not opaque
                {
                    transparent = true;
                    if (src == UBlend.One && dst == UBlend.One) parts.Add("blend_add");
                    else if (src == UBlend.DstColor && dst == UBlend.Zero) parts.Add("blend_mul");
                    else if (src == UBlend.One && dst == UBlend.OneMinusSrcAlpha) parts.Add("blend_premul_alpha");
                    else parts.Add("blend_mix");
                }
            }
            // Cull
            var cull = st != null ? (UCull)(int)st.culling.val : UCull.Back;
            switch (cull)
            {
                case UCull.Off: parts.Add("cull_disabled"); break;
                case UCull.Front: parts.Add("cull_front"); break;
                default: parts.Add("cull_back"); break;
            }
            // Depth write
            if (st != null && (int)st.zWrite.val == 0)
                parts.Add("depth_draw_never");
            // Depth test
            if (st != null)
            {
                var cmp = (UCompare)(int)st.zTest.val;
                if (cmp == UCompare.Always || cmp == UCompare.Disabled)
                    parts.Add("depth_test_disabled");
            }
            if (transparent && !parts.Contains("depth_draw_never"))
            {
                // transparent materials typically don't write depth
                parts.Add("depth_draw_opaque");
            }
            if (parts.Count == 0)
                parts.Add("cull_back");
            return string.Join(", ", parts);
        }

        private static string BuildFragment(Dictionary<string, string> uni,
            List<KeyValuePair<string, UnityTexEnv>> texEnvs,
            List<KeyValuePair<string, Color>> colors,
            List<KeyValuePair<string, float>> floats,
            bool transparent)
        {
            string mainTex = PickName(texEnvs.Select(t => t.Key), "_MainTex", "_BaseMap", "_BaseColorMap", "_MainTexture", "_Albedo", "_AlbedoMap");
            string normalTex = PickName(texEnvs.Select(t => t.Key), "_BumpMap", "_NormalMap", "_Normal");
            string tintCol = PickName(colors.Select(c => c.Key), "_Color", "_BaseColor", "_TintColor", "_Tint");
            string metallic = PickName(floats.Select(f => f.Key), "_Metallic");
            string smooth = PickName(floats.Select(f => f.Key), "_Glossiness", "_Smoothness");
            string rough = PickName(floats.Select(f => f.Key), "_Roughness");

            var sb = new StringBuilder();
            sb.Append("void fragment() {\n");
            if (mainTex != null)
            {
                sb.Append("\tvec4 base_tex = texture(").Append(uni[mainTex]).Append(", UV);\n");
                sb.Append("\tALBEDO = base_tex.rgb");
                if (tintCol != null) sb.Append(" * ").Append(uni[tintCol]).Append(".rgb");
                sb.Append(";\n");
                if (transparent)
                {
                    sb.Append("\tALPHA = base_tex.a");
                    if (tintCol != null) sb.Append(" * ").Append(uni[tintCol]).Append(".a");
                    sb.Append(";\n");
                }
            }
            else if (tintCol != null)
            {
                sb.Append("\tALBEDO = ").Append(uni[tintCol]).Append(".rgb;\n");
                if (transparent) sb.Append("\tALPHA = ").Append(uni[tintCol]).Append(".a;\n");
            }
            else
            {
                sb.Append("\tALBEDO = vec3(0.8);\n");
            }
            if (normalTex != null)
                sb.Append("\tNORMAL_MAP = texture(").Append(uni[normalTex]).Append(", UV).rgb;\n");
            if (metallic != null)
                sb.Append("\tMETALLIC = ").Append(uni[metallic]).Append(";\n");
            if (rough != null)
                sb.Append("\tROUGHNESS = ").Append(uni[rough]).Append(";\n");
            else if (smooth != null)
                sb.Append("\tROUGHNESS = 1.0 - ").Append(uni[smooth]).Append(";\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        private static string PickName(IEnumerable<string> names, params string[] candidates)
        {
            var set = new HashSet<string>(names, StringComparer.OrdinalIgnoreCase);
            foreach (var c in candidates)
                if (set.Contains(c))
                    return names.First(n => string.Equals(n, c, StringComparison.OrdinalIgnoreCase));
            return null;
        }

        // Unity stores both Color and Vector properties in m_Colors (both are float4). Decide which is
        // a real color so we only apply Godot's source_color hint / Color() to actual colors.
        private static bool IsColorProp(string name, Color c, Dictionary<string, SerializedPropertyType> declared)
        {
            if (declared != null && declared.TryGetValue(name, out var t))
                return t == SerializedPropertyType.Color; // Vector -> false, authoritative when known
            var l = name.ToLowerInvariant();
            var looksColor = l.Contains("color") || l.Contains("colour") || l.Contains("tint")
                || l.Contains("emiss") || l.Contains("specular") || l.Contains("ambient")
                || l.Contains("diffuse") || l.Contains("glow") || l.Contains("albedo");
            // A color's channels sit roughly in [0, 16] (allow HDR); rects/coords/rotations blow past that.
            var inColorRange = InRange(c.R) && InRange(c.G) && InRange(c.B) && InRange(c.A);
            return looksColor && inColorRange;
        }

        private static bool InRange(float v) => v >= -0.001f && v <= 16f;

        private static string TextureHint(string prop)
        {
            var p = prop.ToLowerInvariant();
            if (p.Contains("bump") || p.Contains("normal")) return "hint_normal";
            if (p.Contains("main") || p.Contains("albedo") || p.Contains("base") || p.Contains("color") || p.Contains("diffuse"))
                return "source_color";
            return null;
        }

        private static string Vec4(float x, float y, float z, float w) => $"vec4({F(x)}, {F(y)}, {F(z)}, {F(w)})";

        private static string F(float v)
        {
            if (float.IsNaN(v) || float.IsInfinity(v)) v = 0f;
            var s = v.ToString("0.0######", CultureInfo.InvariantCulture);
            return s;
        }

        private static string Sanitize(string name)
        {
            var sb = new StringBuilder(name.Length);
            foreach (var ch in name)
                sb.Append(char.IsLetterOrDigit(ch) || ch == '_' || ch == '-' || ch == '.' ? ch : '_');
            return sb.ToString();
        }

        // Godot 4 identifiers: letters, digits, underscore; cannot start with a digit.
        private static string SanitizeIdent(string name)
        {
            if (string.IsNullOrEmpty(name)) return "_p";
            var sb = new StringBuilder(name.Length);
            foreach (var ch in name)
                sb.Append(char.IsLetterOrDigit(ch) || ch == '_' ? ch : '_');
            if (char.IsDigit(sb[0])) sb.Insert(0, '_');
            return sb.ToString();
        }

    }
}
