using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Globalization;
using System.Linq;
using System.Text;

namespace AssetStudio
{
    /// <summary>
    /// Converts a Unity <see cref="ParticleSystem"/> (read generically from its type tree, so no
    /// hand-written class is needed and it stays version-robust) into a Godot 4 scene (.tscn) holding a
    /// GPUParticles3D node with an embedded ParticleProcessMaterial. Constant / two-constant values map
    /// directly; curve/gradient-driven values are approximated by their scalar and flagged as TODO.
    /// </summary>
    public static class GodotParticleExporter
    {
        public sealed class Result
        {
            public string Name;
            public string Tscn;
            public bool Ok;
        }

        // Unity ParticleSystemShapeType (subset we map)
        private static string MapShape(int unityType, out string extraLines, OrderedDictionary shape)
        {
            extraLines = "";
            float radius = GetF(shape, "radius", 1f);
            if (radius <= 0f) radius = 1f;
            switch (unityType)
            {
                case 0: case 1: case 2: case 3: // Sphere / SphereShell / Hemisphere(Shell)
                    extraLines = $"emission_sphere_radius = {F(radius)}\n";
                    return "1"; // Sphere
                case 5: case 15: case 16: // Box / BoxShell / BoxEdge
                    extraLines = $"emission_box_extents = Vector3({F(radius)}, {F(radius)}, {F(radius)})\n";
                    return "3"; // Box
                case 10: case 11: case 17: // Circle / CircleEdge / Donut
                    extraLines = $"emission_ring_radius = {F(radius)}\nemission_ring_inner_radius = 0.0\nemission_ring_height = 0.0\nemission_ring_axis = Vector3(0, 1, 0)\n";
                    return "6"; // Ring
                default: // Cone family and others -> point emitter with spread (set by caller)
                    return "0"; // Point
            }
        }

        /// <summary>Reusable pieces for embedding a GPUParticles3D into a larger scene.</summary>
        public sealed class Inline
        {
            public string SubResources;   // sub_resource blocks (ids prefixed to stay unique in a scene)
            public int SubCount;          // number of sub_resources emitted (for load_steps)
            public string NodeProps;      // GPUParticles3D property lines (no [node] header)
            public bool Ok;
        }

        public static Result Export(OrderedDictionary root, string name)
        {
            var res = new Result { Name = Sanitize(string.IsNullOrEmpty(name) ? "particles" : name) };
            var inl = BuildInline(root, "p");
            if (!inl.Ok) { res.Tscn = ""; return res; }

            var sb = new StringBuilder();
            sb.Append("[gd_scene load_steps=").Append(inl.SubCount + 1).Append(" format=3]\n\n");
            sb.Append("; Generated by Reunity (AssetStudioMod) from Unity ParticleSystem \"").Append(name).Append("\".\n");
            sb.Append("; Constant values map directly; color-over-lifetime -> color_ramp, size-over-lifetime\n");
            sb.Append("; -> scale_curve. Other curve-driven fields are approximated by their scalar.\n\n");
            sb.Append(inl.SubResources).Append('\n');
            sb.Append("[node name=\"").Append(res.Name).Append("\" type=\"GPUParticles3D\"]\n");
            sb.Append(inl.NodeProps);
            res.Tscn = sb.ToString();
            res.Ok = true;
            return res;
        }

        public static Inline BuildInline(OrderedDictionary root, string idPrefix)
        {
            var inl = new Inline();
            if (root == null) return inl;

            float duration = GetF(root, "lengthInSec", 3f);
            bool looping = GetB(root, "looping", true);
            bool prewarm = GetB(root, "prewarm", false);
            float simSpeed = GetF(root, "simulationSpeed", 1f);

            var initial = GetD(root, "InitialModule");
            var emission = GetD(root, "EmissionModule");
            var shape = GetD(root, "ShapeModule");

            // lifetime
            (float lifeMin, float lifeMax) = ReadCurve(initial, "startLifetime", 3f);
            float lifetime = lifeMax > 0 ? lifeMax : 3f;
            float lifeRand = lifeMax > 0 ? Clamp01((lifeMax - lifeMin) / lifeMax) : 0f;

            // speed / size / rotation / gravity
            (float spMin, float spMax) = ReadCurve(initial, "startSpeed", 1f);
            (float szMin, float szMax) = ReadCurve(initial, "startSize", 1f);
            (float rotMin, float rotMax) = ReadCurve(initial, "startRotation", 0f);
            (float _, float gravMax) = ReadCurve(initial, "gravityModifier", 0f);
            int maxParticles = GetI(initial, "maxNumParticles", 0);

            // emission rate -> amount fallback
            (float _, float rate) = ReadCurve(emission, "rateOverTime", 0f);
            int amount = maxParticles > 0 ? maxParticles : (int)Math.Ceiling(Math.Max(1f, rate * lifetime));
            if (amount <= 0) amount = 8;
            if (amount > 100000) amount = 100000;

            // start color (constant part of the MinMaxGradient)
            var startColor = ReadColor(GetD(initial, "startColor"));

            // shape
            int shapeType = shape != null ? GetI(shape, "type", -1) : -1;
            float shapeAngle = shape != null ? GetF(shape, "angle", 25f) : 25f;
            string emissionShape = "0";
            string shapeExtra = "";
            string spread = "45.0";
            if (shape != null && GetB(shape, "enabled", true))
            {
                emissionShape = MapShape(shapeType, out shapeExtra, shape);
                if (emissionShape == "0") // cone-ish -> point + spread from half-angle
                    spread = F(Math.Min(90f, Math.Max(0f, shapeAngle)));
            }

            float angMinDeg = rotMin * 57.29578f;
            float angMaxDeg = rotMax * 57.29578f;
            float gravY = -9.8f * gravMax;

            // ---- Over-lifetime sub-resources (color gradient, size curve) ----
            var gradId = idPrefix + "_grad";
            var gradTexId = idPrefix + "_gradtex";
            var curveId = idPrefix + "_curve";
            var curveTexId = idPrefix + "_curvetex";
            var ppmId = idPrefix + "_ppm";

            var subResources = new StringBuilder();
            int subCount = 1; // the ParticleProcessMaterial itself

            // Color over lifetime -> Gradient + GradientTexture1D
            string colorRampRef = null;
            var colorModule = GetD(root, "ColorModule");
            if (colorModule != null && GetB(colorModule, "enabled", false))
            {
                var grad = BuildGradient(GetD(colorModule, "gradient"));
                if (grad != null)
                {
                    subResources.Append("[sub_resource type=\"Gradient\" id=\"").Append(gradId).Append("\"]\n").Append(grad).Append('\n');
                    subResources.Append("[sub_resource type=\"GradientTexture1D\" id=\"").Append(gradTexId).Append("\"]\ngradient = SubResource(\"").Append(gradId).Append("\")\n\n");
                    subCount += 2;
                    colorRampRef = gradTexId;
                }
            }

            // Size over lifetime -> Curve + CurveTexture
            string scaleCurveRef = null;
            var sizeModule = GetD(root, "SizeModule");
            if (sizeModule != null && GetB(sizeModule, "enabled", false))
            {
                var curveData = BuildCurve(GetD(GetD(sizeModule, "curve"), "maxCurve"), GetF(GetD(sizeModule, "curve"), "scalar", 1f));
                if (curveData != null)
                {
                    subResources.Append("[sub_resource type=\"Curve\" id=\"").Append(curveId).Append("\"]\n").Append(curveData).Append('\n');
                    subResources.Append("[sub_resource type=\"CurveTexture\" id=\"").Append(curveTexId).Append("\"]\ncurve = SubResource(\"").Append(curveId).Append("\")\n\n");
                    subCount += 2;
                    scaleCurveRef = curveTexId;
                }
            }

            var mat = new StringBuilder();
            mat.Append("[sub_resource type=\"ParticleProcessMaterial\" id=\"").Append(ppmId).Append("\"]\n");
            mat.Append("emission_shape = ").Append(emissionShape).Append('\n');
            mat.Append(shapeExtra);
            mat.Append("direction = Vector3(0, 1, 0)\n");
            mat.Append("spread = ").Append(spread).Append('\n');
            mat.Append("initial_velocity_min = ").Append(F(spMin)).Append('\n');
            mat.Append("initial_velocity_max = ").Append(F(spMax)).Append('\n');
            mat.Append("gravity = Vector3(0, ").Append(F(gravY)).Append(", 0)\n");
            mat.Append("scale_min = ").Append(F(szMin)).Append('\n');
            mat.Append("scale_max = ").Append(F(szMax)).Append('\n');
            if (scaleCurveRef != null)
                mat.Append("scale_curve = SubResource(\"").Append(scaleCurveRef).Append("\")\n");
            if (Math.Abs(angMinDeg) > 0.001f || Math.Abs(angMaxDeg) > 0.001f)
            {
                mat.Append("angle_min = ").Append(F(angMinDeg)).Append('\n');
                mat.Append("angle_max = ").Append(F(angMaxDeg)).Append('\n');
            }
            if (startColor != null)
                mat.Append("color = Color(").Append(startColor).Append(")\n");
            if (colorRampRef != null)
                mat.Append("color_ramp = SubResource(\"").Append(colorRampRef).Append("\")\n");

            var np = new StringBuilder();
            np.Append("amount = ").Append(amount).Append('\n');
            np.Append("lifetime = ").Append(F(lifetime)).Append('\n');
            np.Append("one_shot = ").Append(looping ? "false" : "true").Append('\n');
            if (prewarm) np.Append("preprocess = ").Append(F(duration)).Append('\n');
            if (Math.Abs(simSpeed - 1f) > 0.001f) np.Append("speed_scale = ").Append(F(simSpeed)).Append('\n');
            if (lifeRand > 0.001f) np.Append("lifetime_randomness = ").Append(F(lifeRand)).Append('\n');
            np.Append("process_material = SubResource(\"").Append(ppmId).Append("\")\n");

            inl.SubResources = subResources.ToString() + mat.ToString();
            inl.SubCount = subCount;
            inl.NodeProps = np.ToString();
            inl.Ok = true;
            return inl;
        }

        // ---- type-tree dictionary helpers ----
        private static OrderedDictionary GetD(OrderedDictionary d, string key)
            => d != null && d.Contains(key) ? d[key] as OrderedDictionary : null;

        private static float GetF(OrderedDictionary d, string key, float def)
        {
            if (d == null || !d.Contains(key) || d[key] == null) return def;
            try { return Convert.ToSingle(d[key], CultureInfo.InvariantCulture); } catch { return def; }
        }

        private static int GetI(OrderedDictionary d, string key, int def)
        {
            if (d == null || !d.Contains(key) || d[key] == null) return def;
            try { return Convert.ToInt32(d[key], CultureInfo.InvariantCulture); } catch { return def; }
        }

        private static bool GetB(OrderedDictionary d, string key, bool def)
        {
            if (d == null || !d.Contains(key) || d[key] == null) return def;
            try { return Convert.ToBoolean(d[key]); } catch { return def; }
        }

        // MinMaxCurve: minMaxState 0=const(scalar), 1=curve, 2=twoCurves, 3=twoConstants(minScalar..scalar)
        private static (float min, float max) ReadCurve(OrderedDictionary parent, string key, float def)
        {
            var c = GetD(parent, key);
            if (c == null) return (def, def);
            int state = GetI(c, "minMaxState", 0);
            float scalar = GetF(c, "scalar", def);
            float minScalar = GetF(c, "minScalar", scalar);
            if (state == 3) return (minScalar, scalar);       // two constants
            return (scalar, scalar);                          // constant / curve (approx by scalar)
        }

        // MinMaxGradient: use the constant color (maxColor) when available.
        private static string ReadColor(OrderedDictionary grad)
        {
            if (grad == null) return null;
            var col = GetD(grad, "maxColor") ?? GetD(grad, "minColor");
            if (col == null) return null;
            float r = GetF(col, "r", 1f), g = GetF(col, "g", 1f), b = GetF(col, "b", 1f), a = GetF(col, "a", 1f);
            return $"{F(r)}, {F(g)}, {F(b)}, {F(a)}";
        }

        // Unity MinMaxGradient -> Godot Gradient (offsets + PackedColorArray). Only for gradient states.
        private static string BuildGradient(OrderedDictionary mmg)
        {
            if (mmg == null) return null;
            int state = GetI(mmg, "minMaxState", 0);
            if (state != 1 && state != 3) return null; // 1=gradient, 3=twoGradients (use max)
            var g = GetD(mmg, "maxGradient") ?? GetD(mmg, "minGradient");
            if (g == null) return null;
            int nc = GetI(g, "m_NumColorKeys", 0);
            int na = GetI(g, "m_NumAlphaKeys", 0);
            if (nc <= 0 && na <= 0) return null;

            var colorKeys = new List<(float t, float r, float g, float b)>();
            for (int i = 0; i < nc && i < 8; i++)
            {
                var k = GetD(g, "key" + i);
                float t = GetI(g, "ctime" + i, 0) / 65535f;
                colorKeys.Add((t, GetF(k, "r", 1f), GetF(k, "g", 1f), GetF(k, "b", 1f)));
            }
            var alphaKeys = new List<(float t, float a)>();
            for (int i = 0; i < na && i < 8; i++)
            {
                var k = GetD(g, "key" + i);
                float t = GetI(g, "atime" + i, 0) / 65535f;
                alphaKeys.Add((t, GetF(k, "a", 1f)));
            }
            if (colorKeys.Count == 0) colorKeys.Add((0f, 1f, 1f, 1f));
            if (alphaKeys.Count == 0) alphaKeys.Add((0f, 1f));
            colorKeys.Sort((x, y) => x.t.CompareTo(y.t));
            alphaKeys.Sort((x, y) => x.t.CompareTo(y.t));

            var offsets = new SortedSet<float>();
            foreach (var c in colorKeys) offsets.Add(c.t);
            foreach (var a in alphaKeys) offsets.Add(a.t);

            var sbOff = new StringBuilder();
            var sbCol = new StringBuilder();
            bool first = true;
            foreach (var t in offsets)
            {
                var (r, gg, b) = SampleColor(colorKeys, t);
                float a = SampleAlpha(alphaKeys, t);
                if (!first) { sbOff.Append(", "); sbCol.Append(", "); }
                first = false;
                sbOff.Append(F(t));
                sbCol.Append(F(r)).Append(", ").Append(F(gg)).Append(", ").Append(F(b)).Append(", ").Append(F(a));
            }
            return $"offsets = PackedFloat32Array({sbOff})\ncolors = PackedColorArray({sbCol})\n";
        }

        private static (float r, float g, float b) SampleColor(List<(float t, float r, float g, float b)> keys, float t)
        {
            if (keys.Count == 1 || t <= keys[0].t) return (keys[0].r, keys[0].g, keys[0].b);
            if (t >= keys[keys.Count - 1].t) { var l = keys[keys.Count - 1]; return (l.r, l.g, l.b); }
            for (int i = 1; i < keys.Count; i++)
            {
                if (t <= keys[i].t)
                {
                    var a = keys[i - 1]; var b = keys[i];
                    float f = b.t > a.t ? (t - a.t) / (b.t - a.t) : 0f;
                    return (Lerp(a.r, b.r, f), Lerp(a.g, b.g, f), Lerp(a.b, b.b, f));
                }
            }
            var last = keys[keys.Count - 1];
            return (last.r, last.g, last.b);
        }

        private static float SampleAlpha(List<(float t, float a)> keys, float t)
        {
            if (keys.Count == 1 || t <= keys[0].t) return keys[0].a;
            if (t >= keys[keys.Count - 1].t) return keys[keys.Count - 1].a;
            for (int i = 1; i < keys.Count; i++)
                if (t <= keys[i].t)
                {
                    var a = keys[i - 1]; var b = keys[i];
                    float f = b.t > a.t ? (t - a.t) / (b.t - a.t) : 0f;
                    return Lerp(a.a, b.a, f);
                }
            return keys[keys.Count - 1].a;
        }

        // Unity AnimationCurve -> Godot Curve _data (position, left_tangent, right_tangent, modes).
        private static string BuildCurve(OrderedDictionary animCurve, float scalar)
        {
            if (animCurve == null) return null;
            if (!(animCurve["m_Curve"] is object[] pts) || pts.Length == 0) return null;
            if (scalar == 0f) scalar = 1f;
            var data = new StringBuilder();
            float maxVal = 0f;
            int count = 0;
            for (int i = 0; i < pts.Length; i++)
            {
                if (!(pts[i] is OrderedDictionary kf)) continue;
                float time = GetF(kf, "time", 0f);
                float val = GetF(kf, "value", 0f) * scalar;
                float inSlope = GetF(kf, "inSlope", 0f) * scalar;
                float outSlope = GetF(kf, "outSlope", 0f) * scalar;
                if (Math.Abs(val) > maxVal) maxVal = Math.Abs(val);
                if (count > 0) data.Append(", ");
                data.Append("Vector2(").Append(F(time)).Append(", ").Append(F(val)).Append("), ")
                    .Append(F(inSlope)).Append(", ").Append(F(outSlope)).Append(", 0, 0");
                count++;
            }
            if (count == 0) return null;
            var sb = new StringBuilder();
            if (maxVal > 1f) sb.Append("max_value = ").Append(F(maxVal)).Append('\n');
            sb.Append("_data = [").Append(data).Append("]\n");
            sb.Append("point_count = ").Append(count).Append('\n');
            return sb.ToString();
        }

        private static float Lerp(float a, float b, float t) => a + (b - a) * t;

        private static float Clamp01(float v) => v < 0f ? 0f : (v > 1f ? 1f : v);

        private static string F(float v)
        {
            if (float.IsNaN(v) || float.IsInfinity(v) || v == 0f) return "0.0"; // also normalizes -0.0
            return v.ToString("0.0######", CultureInfo.InvariantCulture);
        }

        private static string Sanitize(string name)
        {
            var sb = new StringBuilder(name.Length);
            foreach (var ch in name)
                sb.Append(char.IsLetterOrDigit(ch) || ch == '_' || ch == '-' || ch == '.' ? ch : '_');
            return sb.ToString();
        }
    }
}
