using AssetStudio;
using AssetStudioCLI.Options;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using static AssetStudioCLI.Exporter;
using Ansi = AssetStudio.ColorConsole;

namespace AssetStudioCLI
{
    /// <summary>
    /// "-m godotscene": export the loaded scene as glTF model(s) (reusing the proven glTF exporter, which
    /// handles the Unity->right-handed coordinate conversion, materials, skinning and node animations) plus
    /// a Godot 4 scene (.tscn) that instances each exported model under a single Node3D root. Godot 4 imports
    /// glTF natively, so opening scene.tscn shows the 3D scene with correct orientation and materials.
    /// </summary>
    internal static partial class Studio
    {
        public static void ExportGodotScene()
        {
            var outRoot = CLIOptions.o_outputFolder.Value;
            var modelsDir = Path.Combine(outRoot, "models");

            // Collect root GameObjects that have a mesh somewhere in their subtree (same rule as splitObjects).
            var roots = new List<GameObject>();
            foreach (var fileNode in gameObjectTree)
            {
                foreach (GameObjectNode rootNode in fileNode.nodes)
                {
                    var gos = new List<GameObject>();
                    CollectNode(rootNode, gos);
                    if (gos.Any(x => x.m_SkinnedMeshRenderer != null || x.m_MeshFilter != null))
                        roots.Add(rootNode.gameObject);
                }
            }

            if (roots.Count == 0)
            {
                Logger.Warning("No 3D objects (mesh roots) found to build a Godot scene. Point at a scene/prefab bundle or the game's *_Data folder.");
                return;
            }

            Logger.Info($"Exporting {roots.Count} model root(s) to glTF and assembling a Godot scene...");
            Directory.CreateDirectory(modelsDir);

            var gltfSettings = new Gltf.Settings { Format = Gltf.Format.Glb, ExportAnimations = true, ScaleFactor = 1.0f };
            var usedNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            var instances = new List<(string node, string res)>();
            var overwrite = CLIOptions.f_overwriteExisting.Value;
            var exported = 0;

            foreach (var go in roots)
            {
                var name = UniqueSceneName(string.IsNullOrEmpty(go.m_Name) ? "Object" : FixFileName(go.m_Name), usedNames);
                var glbPath = Path.Combine(modelsDir, name + ".glb");
                try
                {
                    if (overwrite || !File.Exists(glbPath))
                    {
                        var convert = new ModelConverter(go, ImageFormat.Png);
                        ModelExporter.ExportGltf(glbPath, convert, gltfSettings);
                    }
                    instances.Add((name, "res://models/" + name + ".glb"));
                    exported++;
                }
                catch (Exception ex)
                {
                    Logger.Warning($"Failed to export \"{go.m_Name}\" to glTF: {ex.Message}");
                }
            }

            if (instances.Count == 0)
            {
                Logger.Error("Nothing was exported; Godot scene not written.");
                return;
            }

            // Build scene.tscn instancing every exported glb.
            var ext = new StringBuilder();
            var nodes = new StringBuilder();
            for (var i = 0; i < instances.Count; i++)
            {
                var id = $"m{i + 1}";
                ext.Append("[ext_resource type=\"PackedScene\" path=\"").Append(instances[i].res).Append("\" id=\"").Append(id).Append("\"]\n");
                nodes.Append("[node name=\"").Append(instances[i].node).Append("\" parent=\".\" instance=ExtResource(\"").Append(id).Append("\")]\n");
            }

            var sb = new StringBuilder();
            sb.Append("[gd_scene load_steps=").Append(instances.Count + 1).Append(" format=3]\n\n");
            sb.Append("; Generated by Reunity (AssetStudioMod). Unity scene -> Godot 4.\n");
            sb.Append("; Each child instances a glTF model exported from a Unity GameObject root.\n\n");
            sb.Append(ext).Append('\n');
            sb.Append("[node name=\"Scene\" type=\"Node3D\"]\n\n");
            sb.Append(nodes);

            var scenePath = Path.Combine(outRoot, "scene.tscn");
            File.WriteAllText(scenePath, sb.ToString());

            // Make the output folder open directly as a Godot 4 project (don't clobber an existing one).
            var projectFile = Path.Combine(outRoot, "project.godot");
            if (!File.Exists(projectFile))
            {
                File.WriteAllText(projectFile,
                    "config_version=5\n\n" +
                    "[application]\n" +
                    "config/name=\"Reunity Imported Scene\"\n" +
                    "run/main_scene=\"res://scene.tscn\"\n" +
                    "config/features=PackedStringArray(\"4.4\")\n\n" +
                    "[rendering]\n" +
                    "renderer/rendering_method=\"gl_compatibility\"\n");
            }

            Logger.Info($"Exported {exported.ToString().Color(Ansi.BrightGreen)} model(s) to \"{modelsDir.Color(Ansi.BrightCyan)}\" and wrote \"{scenePath.Color(Ansi.BrightCyan)}\".");
            Logger.Info("Open the output folder in Godot 4 (it is a ready project); Godot imports the .glb files on open, then run scene.tscn.");
        }

        private static string UniqueSceneName(string baseName, HashSet<string> used)
        {
            var name = string.IsNullOrEmpty(baseName) ? "Object" : baseName;
            var candidate = name;
            var n = 1;
            while (!used.Add(candidate))
                candidate = $"{name}_{n++}";
            return candidate;
        }
    }
}
